"""Initial migration

Revision ID: 1765a527bd86
Revises: 
Create Date: 2020-08-17 20:00:37.333268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1765a527bd86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_user')
    op.alter_column('employee', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employee', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'employee', ['username'])
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'post', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'employee', type_='unique')
    op.alter_column('employee', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employee', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('new_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='new_user_pkey')
    )
    # ### end Alembic commands ###
